### ISSUE TITLE
`□EMT□□情歌` -> `对EMT献上情歌`

### ISSUE THREAD

**Issue by lqian35** [CCXXXI/re0wiki#317]
### 检查重复提议

- [X] 该译名未被提出过

### 新译名的来源

台版

### 为什么新译名比旧译名更好？

原译名明显是系统错误。

**Comment by CanopusEtaCarinae** [comment]
群里刚转发了两小段聊天纪录大致涉及了标题之所以这么写的由来。Tom巨佬可以去看看

**Comment by CCXXXI** [comment]
补一下相关讨论记录

<details><summary>第一段</summary>
<p>

【devil】Prometheus_17th 2020/11/27 16:01:45
原文没有谓语，这样说懂了？

【船底】α Carinae/Canopus 2020/11/27 16:01:47
所以那个日文标题直译是没法译的么

【船底】α Carinae/Canopus 2020/11/27 16:01:59
噢，现在才懂

【船底】α Carinae/Canopus 2020/11/27 16:02:02
对不起

【Lab008】莱月桑 2020/11/27 16:02:26
（话说编写规范不是说天角>民汉>台角吗）

【船底】α Carinae/Canopus 2020/11/27 16:04:20
所以我又恶心人了，就这样

【Lab008】莱月桑 2020/11/27 16:05:49
我按编写规范先把天角的打上去算了

【Lab008】莱月桑 2020/11/27 16:05:50

</p>
</details> 

<details><summary>第二段</summary>
<p>

【devil】Prometheus_17th 2020/12/22 0:18:39
?你想表达神额么

【devil】Prometheus_17th 2020/12/22 0:18:58
就 这 个

【Lab008】莱月桑 2020/12/22 0:19:58


【Lab008】莱月桑 2020/12/22 0:20:17
我以为黑方块是待填的意思

【devil】Prometheus_17th 2020/12/22 0:20:43
你去吧web第六章的73 74节填一下

【船底】α Carinae/Canopus 2020/12/22 0:20:44
是日语原文没有谓语

【船底】α Carinae/Canopus 2020/12/22 0:21:13
当初因为不懂日语在群里脸被打烂了

</p>
</details>
